aoomuki_comp/app/urls.py
from django.urls import path, re_path
from app import views
from django.contrib.auth import views as auth_views
# from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'app'

urlpatterns = [
    # Matches any html file - to be used for gentella
    # Avoid using your .html in your resources.
    # Or create a separate django app.
    re_path(r'^.*\.html', views.gentella_html, name='gentella'),

    # The home page
    path('', views.index, name='index'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('Enregistrement/', views.register, name='Enregistrement'),
    path('logout/', auth_views.LogoutView.as_view(next_page='app:login'), name='logout'),
    # path('Formulaire_Compétences_Collaborateur/', views.AllFormlist, name='Formulaire_Compétences_Collaborateur'),
    # path('Ajouter_un_utilisateur/collaborateur', views.AddCollaborater, name='Ajouter_un_utilisateur/collaborateur'),
    path('search/', views.search, name='search'),
    path('Liste_des_collaborateurs/', views.ListCollaboraters, name='Liste_des_collaborateurs'),
    path('Liste_des_utilisateurs/', views.ListUsers, name='Liste_des_utilisateurs'),
    path('Liste_des_domaines/', views.ListField, name='Liste_des_domaines'),
    path('Liste_des_compétences/', views.ListCompetence, name='Liste_des_compétences'),
    path('Liste_des_certifications/', views.ListOfCertification, name='Liste_des_certifications'),
    path('Liste_des_sociétés/', views.ListSociety, name='Liste_des_sociétés'),
    path('Ajouter_Domaines_Compétences/', views.AddFieldCompDegreeSociety, name='Ajouter_Domaines_Compétences'),
    path('Ajouter_un_collaborateur/', views.AddCollabForm, name='Ajouter_un_collaborateur'),
    path('GraphComp/', views.CompetencesGraph, name='GraphComp'),
    # re_path(r'^Profil/(?P<user_id>[0-9]+)/$', views.ProfilsAdmin, name='Profils'),
    re_path(r'^(?P<collaborater_id>[0-9]+)/$', views.Profils, name='Profils'),
    # re_path(r'^GraphCollab(?P<user_id>[0-9]+)/$', views.CompetencesGraphCollab, name='GraphCollab'),
    re_path(r'^DeleteCollab/(?P<collaborater_id>[0-9]+)/$', views.DeleteCollab, name='DeleteCollab'),
    re_path(r'^DeleteUser/(?P<user_id>[0-9]+)/$', views.DeleteUser, name='DeleteUser'),
    re_path(r'^Mon_profil/(?P<user_id>[0-9]+)/$', views.CollaboraterProfil, name='Mon_profil'),
    re_path(r'^Modifier_des_certifications/(?P<profil_id>[0-9]+)/$', views.ModifyInfoCollab, name='Modifier_des_certifications'),
    re_path(r'^Modifier_des_compétences/(?P<listcompetence_id>[0-9]+)/$', views.ModifyCompetenceCollab, name='Modifier_des_compétences'),
    re_path(r'^Ajouter_des_compétences/(?P<user_id>[0-9]+)/$', views.AddCompetenceCollab, name='Ajouter_des_compétences'),
    re_path(r'^Ajouter_des_informations_générales/(?P<user_id>[0-9]+)/$', views.AddInfoCollab, name='Ajouter_des_informations_générales'),
]

aoomuki_comp/gentelella/urls.py
from django.conf.urls import url, include
from django.contrib import admin
# from django.urls import path
# from django.views.generic.base import TemplateView 

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^', include("django.contrib.auth.urls")), 
    # path('accounts/', include('django.contrib.auth.urls')),
    # path('', TemplateView.as_view(template_name='app/index.html'), name='index'),     # app/ -> Genetelella UI and resources

    # url(r'^app/', include('app.urls')),
    url(r'^', include('app.urls')),


]

aoomuki_comp/app/templates/app/Certification_List.html
{% extends "app/base_site.html" %}

{% block content %}
<div class="right_col" role="main">
    <div class="">
    <a href="javascript:history.go(-1)">Retour</a>

        <div class="text-center">
            <h1>LISTE DES CERTIFICATIONS</h1>
            <a href="{% url 'app:Ajouter_Domaines_Compétences' %}">Ajouter une certification</a>
        </div>
        <div class="text-center text-success " >
            {% if messages %}
                {% for message in messages %}
                    <h3>{{ message }}</h3>
                {% endfor %}
            {% endif %}
        </div>
        <div class="page-title">
            <div class="row">
                <div class="col-md-12 ">
                    <table class="mb-5 mt-5">
                        {% for certification in certification%}
                            <p>{{ certification.name | upper}}</p>
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

aoomuki_comp/app/templates/app/FormModifyCompetenceCollab.html
{% extends 'app/base_site.html' %}

{% block content %} 
<div class="right_col" role="main">
    <div class="">
    <a href="javascript:history.go(-1)">Retour</a>
        <div class="page-title">
            {% if user.is_authenticated%}
                {% comment %} {% for profil in profil %}
                    {% if profil.user_id == user.id%}  {% endcomment %}
                <div class="col-12 text-center">
                    <h1>{{ user.last_name }} {{ user.first_name }}</h1>
                    <h2>{{ profil.society.name }}</h2>
                    <h2>{{ profil.workstation.name }}</h2>

                </div>
            {% comment %} {% endif %}
            {% endfor %} {% endcomment %}
            {% endif %}
                <div class="">
                <div class="text-center text-success " >
                    {% if messages %}
                        {% for message in messages %}
                            <h3>{{ message }}</h3>
                        {% endfor %}
                    {% endif %}
                </div> 
                    <div class="col-md-12"> 
                    <div id=""></div>
                        <div>
                        <form method="POST" class="post-form" class="my-ajax-form" >
                                {% csrf_token %}
                                {{ form3.as_p}}
                                <button type="submit" name="btnform2" class="save btn btn-default">VALIDER</button>
                        </form> 
                        </div>
                    </div> 
                </div>
        </div>
    </div>
</div>
{% endblock %}

aoomuki_comp/app/templates/app/GraphCompetencesCollab.html
{% block content %} 
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<div class="right_col" role="main">
    <div class="">
          <div class="col-md-6">
           <canvas id="Chart1"></canvas>
             {% comment %} <canvas class="pie" height="140" width="140" style="margin: 15px 10px 10px 0"></canvas> {% endcomment %}
          </div>
    </div>
</div>

{% block javascripts %} 
<script>
$(document).ready(function(){ 
  var ctx = document.getElementById('Chart1').getContext('2d');
    var chart = new Chart(ctx, {
      // The type of chart we want to create
      type: 'bar',

      // The data for our dataset
      data: {
        labels: [{% for item in qs %} '{{item.Competence}}',{% endfor %}]
        datasets: [{
          label: 'My First dataset',
          backgroundColor: 'rgb(255, 99, 132)',
          borderColor: 'rgb(255, 99, 132)',
          data: {% for item in qs %} {{item.ListLevel}},{% endfor %}
        }]
      },

      // Configuration options go here
      options: {}
    });
});
</script>
{% endblock javascripts %}


{% endblock %}

aoomuki_comp/app/templates/app/Society_List.html
{% extends "app/base_site.html" %}

{% block content %}
<div class="right_col" role="main">
    <div class="">
    <a href="javascript:history.go(-1)">Retour</a>
        <div class="text-center">
            <h1>LISTE DES SOCIÉTÉS</h1>
            <a href="{% url 'app:Ajouter_Domaines_Compétences' %}">Ajouter une société</a>
        </div>
        <div class="text-center text-success " >
            {% if messages %}
                {% for message in messages %}
                    <h3>{{ message }}</h3>
                {% endfor %}
            {% endif %}
        </div>
        <div class="page-title">
            <div class="row">
                <div class="col-md-12 ">
                    <table class="mb-5 mt-5">
                        {% for society in society%}
                            <p>{{ society.name | upper}}</p>
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

aoomuki_comp/app/templates/app/User_List.html
{% extends 'app/base_.html' %}

{% block content %} 

<div class="right_col" role="main">
    <div class="">
    <a href="javascript:history.go(-1)">Retour</a>
        <div class="page-title">
            <div>

                <div class="text-center">
                <h1>LISTE DES UTILISATEURS</h1>
                </div>
                {% comment %} {% include 'app/search_form.html' %} {% endcomment %}
                <table class="mb-5 mt-5">
                    {% comment %} <tr>
                        <th class="text-warning" scope="col">NOM / PRENOM</th>
                        <th class="text-warning" scope="col">SOCIETE</th>
                    </tr> {% endcomment %}
                    {% for user in users %}


                    <tr height="50">
                        <td width="200" scope="row">
                            <p>{{ user.last_name | upper }} {{ user.first_name }}</p>
                            <hr>
                        </td>
                        {% for profil in profil %}
                        {% if user.id == profil.user_id %}
                        <td width="200">
                            <p>{{ profil.society.name }}</p>
                            <hr>
                        </td>
                        {% else %}
                        <p></p> 
                                                {% endif %}{% endfor %}

                        <td width="200">
                            <form class="form-inline" action="{% url 'app:DeleteUser' user_id=user.id %}"  method="post" onclick="return confirm('Etes vous sur de vouloir supprimer {{ user.Lastname }} {{ user.Firstname }} ');">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger btn-sm">Supprimer l'utilisateur</button>
                            </form> 
                            <hr>
                        </td>
                        {% comment %} {% for profil in profil %}
                        {% if user.id == profil.user_id %}

                        <td width="200">
                            <form class="form-inline" action="{% url 'app:Profils' user_id=user.id %}"  method="post">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger btn-sm">Voir le profil Collaborateur</button>
                            </form> 
                            <hr>
                        </td>
                        {% else %}
                        <p></p>
                        {% endif %}{% endfor %} {% endcomment %}
                    </tr>
                                                            {% comment %} {% endif %}

                                        {% endfor %} {% endcomment %}

                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
</div>


{% endblock %} 

aoomuki_comp/app/templates/app/base_site.html
<!DOCTYPE html>
<html lang="fr">
  <head>
    {% block head %}
      {% block meta %}
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <!-- Meta, title, CSS, favicons, etc. -->
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
      {% endblock meta %}

      <title>Aoomuki competences  | {% block title %}{% endblock %}</title>
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-v4-grid-only@1.0.0/dist/bootstrap-grid.min.css">

      {% block stylesheets %}
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7/jquery.js"></script> 
        <script src="http://malsup.github.com/jquery.form.js"></script> 
        <!-- Bootstrap -->
        <link href="/static/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
        <!-- Font Awesome -->
        <link href="/static/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
        <!-- NProgress -->
        <link href="/static/vendors/nprogress/nprogress.css" rel="stylesheet">
        <!-- bootstrap-daterangepicker -->
        <link href="/static/vendors/bootstrap-daterangepicker/daterangepicker.css" rel="stylesheet">
        <!-- iCheck -->
        <link href="/static/vendors/iCheck/skins/flat/green.css" rel="stylesheet">
        <!-- bootstrap-progressbar -->
        <link href="/static/vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css" rel="stylesheet">
        <!-- JQVMap -->
        <link href="/static/vendors/jqvmap/dist/jqvmap.min.css" rel="stylesheet"/>
      {% endblock stylesheets %}
      <!-- Custom Theme Style -->
      <link href="/static/build/css/custom.css" rel="stylesheet">
    {% endblock head %}
  </head>

  <body class="{% block body_class %}nav-md {% endblock body_class %}">
    {% block body %}
      <div class="container body">
        <div class="main_container">

          {% block sidebar %}
            <div class="col-md-3 left_col {% block sidebar_class %} {% endblock sidebar_class %}">
              {% include "app/sidebar.html" %}
            </div>
          {% endblock sidebar %}

          {% block top_navigation %}
            <div class="top_nav">
              {% include "app/top_navigation.html" %}
            </div>
          {% endblock top_navigation %}

          {% block content %}
            <!-- {{ content }} -->
          {% endblock content %}

          {% block footer %}
            <footer>
              {% include "app/footer.html" %}
            </footer>
          {% endblock footer %}
        </div>
      </div>

      {% block javascripts %}
        <!-- jQuery -->
        <script src="/static/vendors/jquery/dist/jquery.min.js"></script>
        <!-- Bootstrap -->
        <script src="/static/vendors/bootstrap/dist/js/bootstrap.min.js"></script>
        <!-- FastClick -->
        <script src="/static/vendors/fastclick/lib/fastclick.js"></script>
        <!-- NProgress -->
        <script src="/static/vendors/nprogress/nprogress.js"></script>
        <!-- bootstrap-progressbar -->
        <script src="/static/vendors/bootstrap-progressbar/bootstrap-progressbar.min.js"></script>
        <!-- iCheck -->
        <script src="/static/vendors/iCheck/icheck.min.js"></script>
        <!-- bootstrap-daterangepicker -->
        <script src="/static/vendors/moment/min/moment.min.js"></script>
        <script src="/static/vendors/bootstrap-daterangepicker/daterangepicker.js"></script>
        <!-- bootstrap-wysiwyg -->
        <script src="/static/vendors/bootstrap-wysiwyg/js/bootstrap-wysiwyg.min.js"></script>
        <script src="/static/vendors/jquery.hotkeys/jquery.hotkeys.js"></script>
        <script src="/static/vendors/google-code-prettify/src/prettify.js"></script>
        <!-- jQuery Tags Input -->
        <script src="/static/vendors/jquery.tagsinput/src/jquery.tagsinput.js"></script>
        <!-- Switchery -->
        <script src="/static/vendors/switchery/dist/switchery.min.js"></script>
        <!-- Select2 -->
        <script src="/static/vendors/select2/dist/js/select2.full.min.js"></script>
        <!-- Parsley -->
        <script src="/static/vendors/parsleyjs/dist/parsley.min.js"></script>
        <!-- Autosize -->
        <script src="/static/vendors/autosize/dist/autosize.min.js"></script>
        <!-- jQuery autocomplete -->
        <script src="/static/vendors/devbridge-autocomplete/dist/jquery.autocomplete.min.js"></script>
        <!-- starrr -->
        <script src="/static/vendors/starrr/dist/starrr.js"></script>
        {% comment %} <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.min.js"></script>
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js"></script> {% endcomment %}
        {% comment %} <script src="/static/vendors/Chart.js/dist/chart.min.js"></script> {% endcomment %}

      {% endblock %}
      <!-- Custom Theme Scripts -->
      <script src="/static/build/js/custom.js"></script>
    {% endblock body %}
  </body>
</html>

aoomuki_comp/app/templates/app/profil.html
{% extends 'app/base_site.html' %}

{% block content %} 
<div class="right_col" role="main">
    <div class="">
        <div class="page-title">
            <div class="">
            <a href="javascript:history.go(-1)">Retour</a>
            {% for profil in profil %}
            {% for user in user %}
            {% if profil.user_id == collaborater.user_id %}
            {% if profil.user_id == user.id %}
                <div class="col-12 text-center">
                    <h1>{{ user.last_name }} {{ user.first_name }}</h1>
                    <h2>{{ profil.society.name }}</h2>
                    <h2>{{ profil.workstation.name }}</h2>
                    {% comment %} <form class="form-inline" action="{% url 'app:DeleteCollab' collaborater_id=collaborater.id %}"  method="post" onclick="return confirm('Etes vous sur de vouloir supprimer {{ collaborater.Lastname }} {{ collaborater.Firstname }} ');">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger btn-sm">Supprimer le collaborateur</button>
                    </form>  {% endcomment %}
                </div>
                <div class="row border border-success">
                    <div class="col-md-12 text-center text-danger ">
                        <h3>CERTIFICATIONS</h3>
                    </div>
                </div>
                <div class="row mt-5">
                    <div class="col-md-12 text-center ">
                        {% for certification in profil.certification.all %}
                        <li>{{ certification.name}}</li>
                        {% endfor %}
                    </div>
                </div>
                <div class="row ">
                    <div class="col-md-12 text-center text-danger ">
                        <h3>DOMAINES / COMPÉTENCES</h3>
                    </div>
                </div>
                <div class="row">
                    {% for field in field %}

                    <div class="col-md-12 ">
                        <table class="mb-5 mt-5">
                            <h4 class="text-danger">{{ field.name}}</h4>
                            <tr>
                                <th class="text-warning" scope="col">Compétence</th>
                                <th class="text-warning" scope="col">Niveau</th>
                                <th class="text-warning" scope="col">Intérêt</th>
                            </tr>
                                {% comment %} {% for user in user%}
                                {% if collaborater.user_id == User.id %} {% endcomment %}

                                {% for listcompetence in listcompetence%}
                                {% if listcompetence.User_id == profil.user_id %}

                                {% for competence in competence%}
                                {% if competence.field_id == field.id %}
                                {% if listcompetence.Competence_id == competence.id %}
                                {% for level in level%}
                                {% if listcompetence.ListLevel_id == level.id %}
                                {% for interest in interest%}
                                {% if listcompetence.ListInterest_id == interest.id %}
                                    <tr height="50">
                                        <td width="400" scope="row">
                                            <p>{{ competence.name }}</p>
                                        </td>
                                        <td width="200" scope="row">
                                            <p>{{ level.value }}</p>
                                        </td>
                                        <td width="400" scope="row">
                                            <p>{{ interest.value }}</p>
                                        </td>
                                    </tr>
                                {% endif %}
                                {% endfor %}
                                {% endif %}
                                {% endfor %}
                                {% endif %}
                                {% endif %}
                                {% endfor %}

                                {% endif %}
                                {% endfor %}
                                {% comment %} {% endif %}
                                {% endfor %} {% endcomment %}
                        </table>
                    </div>
                    {% endfor %}
                </div>
                    {% endif %}
                    {% endif %}
                    {% endfor %}
                                        {% endfor %}

                    {% comment %} {% endfor %} {% endcomment %}
            </div>
        </div>
    </div>
</div>
{% endblock %} 


{% comment %} <div class="col-md-12 text-center">
    <p>{{ collaborater.Lastname }} {{ collaborater.Firstname }}</p> {% endcomment %}
    {% comment %} <li>{{ collaborater.competences__name }}</li> {% endcomment %}
    {% comment %} <li>{{ interests_value }}</li> {% endcomment %}
{% comment %} </div> {% endcomment %}


{% comment %} {% for collaborater in collaboraters %} {% endcomment %}
 {% comment %} <p>{{ collaboraters_lastname }} {{ collaboraters_firstname }}</p>
    <li>{{ competences_name }}</li> {% endcomment %}

    {% comment %} <p>{{ interest_name }}</p> {% endcomment %}
{% comment %} {% endfor%} {% endcomment %}




{% comment %} {% for listcompetence in listcompetence%}
                                    {% for competence in competence%}
                                        {% if listcompetence.Collaborater_id == collaborater.id %}
                                            {% if listcompetence.Competence_id == competence.id %}
                                            {% if listcompetence.ListInterest_id == ListInterest.id %}
                                            {% if listcompetence.ListLevel_id == ListLevel.id %}

                                                {% if competence.field_id == field.id %}
                                                <tr height="50">
                                                    <td width="400" scope="row">
                                                        <p>{{ competence.name }}</p>
                                                    </td>
                                                    <td width="400" scope="row">
                                                        <p{{ ListInterest.value }}></p>
                                                    </td>
                                                    <td width="400" scope="row">
                                                        <p>{{ ListLevel.value }}</p>
                                                    </td>
                                                </tr> {% endcomment %}

aoomuki_comp/app/templates/app/sidebar.html
<div class="left_col scroll-view">
  <div class="navbar nav_title" style="border: 0;">
    <a href="{% url 'app:index' %}" class="site_title"><i class="fa fa-spinner"></i> <span>Aoomuki | Accueil</span></a>
  </div>

  <div class="clearfix"></div>

  <!-- menu profile quick info -->
  <div class="profile clearfix">
    <div class="profile_pic">
      <img src="/static/images/img.jpg" alt="..." class="img-circle profile_img">
    </div>
    <div class="profile_info">
    {% comment %} {% if user.is_authenticated %}
      <span>Bonjour,</span>
      <h2>{{user.Lastname}} {{user.Firstname}}</h2>
    {% else %}
<p>Vous n'etes pas connecté</p>
{% endif %} {% endcomment %}
      <span>Bonjour {{user.last_name}} {{user.first_name}}</span>
      {% comment %} <h2>{{ request.user}}</h2> {% endcomment %}
    </div>
  </div>
  <!-- /menu profile quick info -->

  <br />

  <!-- sidebar menu -->
  <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
    <div class="menu_section">
      <h3>General</h3>
      <ul class="nav side-menu">
         <li><a><i class="fa fa-edit"></i> MENU <span class="fa fa-chevron-down"></span></a>
          <ul class="nav child_menu">
            {% if user.is_authenticated %}
              {% if user.is_staff == False %}
            <li><a href="{% url 'app:Ajouter_des_informations_générales' user_id=user.id %}">1/ Créer mon profil</a></li>
            <li><a href="{% url 'app:Ajouter_des_compétences' user_id=user.id %}">2/ Formulaire Compétences Collaborateur</a></li>
            <li><a href="{% url 'app:Mon_profil' user_id=user.id %}">Mon profil</a></li>
            {% else %}
            <li><a href="{% url 'app:Mon_profil' user_id=user.id %}">Mon profil</a></li>
            <li><a href="{% url 'app:Ajouter_des_informations_générales' user_id=user.id %}">Formulaire Informations générales</a></li>
            <li><a href="{% url 'app:Ajouter_des_compétences' user_id=user.id %}">Formulaire Compétences Collaborateur</a></li>
            <li><a href="{% url 'app:Liste_des_utilisateurs' %}">Liste des utilisateurs</a></li>
            <li><a href="{% url 'app:Enregistrement' %}">Ajouter un utilisateur</a></li>
            <li><a href="{% url 'app:Liste_des_collaborateurs' %}">Liste des collaborateurs</a></li>
            <li><a href="{% url 'app:Ajouter_un_collaborateur' %}">Ajouter un collaborater</a></li>
            <li><a href="{% url 'app:Liste_des_domaines' %}">Liste des domaines</a></li>
            <li><a href="{% url 'app:Liste_des_compétences' %}">Liste des compétences</a></li>
            <li><a href="{% url 'app:Liste_des_certifications' %}">Liste des certifications</a></li>
            <li><a href="{% url 'app:Liste_des_sociétés' %}">Liste des sociétés</a></li>
            <li><a href="{% url 'app:Ajouter_Domaines_Compétences' %}">Ajouter Domaines / Compétences / Certifications / Sociétés</a></li>
            <li><a href="{% url 'app:GraphComp' %}">GraphComp</a></li>

            {% endif %}
                {% endif %}
          </ul>
        </li> 
        {% comment %} <li><a><i class="fa fa-desktop"></i> UI Elements <span class="fa fa-chevron-down"></span></a>
          <ul class="nav child_menu">
            <li><a href="general_elements.html">General Elements</a></li>
            <li><a href="media_gallery.html">Media Gallery</a></li>
            <li><a href="typography.html">Typography</a></li>
            <li><a href="icons.html">Icons</a></li>
            <li><a href="glyphicons.html">Glyphicons</a></li>
            <li><a href="widgets.html">Widgets</a></li>
            <li><a href="invoice.html">Invoice</a></li>
            <li><a href="inbox.html">Inbox</a></li>
            <li><a href="calendar.html">Calendar</a></li>
          </ul>
        </li>
        <li><a><i class="fa fa-table"></i> Tables <span class="fa fa-chevron-down"></span></a>
          <ul class="nav child_menu">
            <li><a href="tables.html">Tables</a></li>
            <li><a href="tables_dynamic.html">Table Dynamic</a></li>
          </ul>
        </li>
        <li><a><i class="fa fa-bar-chart-o"></i> Data Presentation <span class="fa fa-chevron-down"></span></a>
          <ul class="nav child_menu">
            <li><a href="chartjs.html">Chart JS</a></li>
            <li><a href="chartjs2.html">Chart JS2</a></li>
            <li><a href="morisjs.html">Moris JS</a></li>
            <li><a href="echarts.html">ECharts</a></li>
            <li><a href="other_charts.html">Other Charts</a></li>
          </ul>
        </li>
        <li><a><i class="fa fa-clone"></i>Layouts <span class="fa fa-chevron-down"></span></a>
          <ul class="nav child_menu">
            <li><a href="fixed_sidebar.html">Fixed Sidebar</a></li>
            <li><a href="fixed_footer.html">Fixed Footer</a></li>
          </ul>
        </li>
      </ul> {% endcomment %}
    </div>
    <div class="menu_section">
      {% comment %} <h3>Live On</h3>
      <ul class="nav side-menu">
        <li><a><i class="fa fa-bug"></i> Additional Pages <span class="fa fa-chevron-down"></span></a>
          <ul class="nav child_menu">
            <li><a href="e_commerce.html">E-commerce</a></li>
            <li><a href="projects.html">Projects</a></li>
            <li><a href="project_detail.html">Project Detail</a></li>
            <li><a href="contacts.html">Contacts</a></li>
            <li><a href="profile.html">Profile</a></li>
          </ul>
        </li>
        <li><a><i class="fa fa-windows"></i> Extras <span class="fa fa-chevron-down"></span></a>
          <ul class="nav child_menu">
            <li><a href="page_403.html">403 Error</a></li>
            <li><a href="page_404.html">404 Error</a></li>
            <li><a href="page_500.html">500 Error</a></li>
            <li><a href="plain_page.html">Plain Page</a></li>
            <li><a href="login.html">Login Page</a></li>
            <li><a href="pricing_tables.html">Pricing Tables</a></li>
          </ul>
        </li>
        <li><a><i class="fa fa-sitemap"></i> Multilevel Menu <span class="fa fa-chevron-down"></span></a>
          <ul class="nav child_menu">
              <li><a href="#level1_1">Level One</a>
              <li><a>Level One<span class="fa fa-chevron-down"></span></a>
                <ul class="nav child_menu">
                  <li class="sub_menu"><a href="level2.html">Level Two</a>
                  </li>
                  <li><a href="#level2_1">Level Two</a>
                  </li>
                  <li><a href="#level2_2">Level Two</a>
                  </li>
                </ul>
              </li>
              <li><a href="#level1_2">Level One</a>
              </li>
          </ul>
        </li>
        <li><a href="javascript:void(0)"><i class="fa fa-laptop"></i> Landing Page <span class="label label-success pull-right">Coming Soon</span></a></li>
      </ul> {% endcomment %}
    </div>
  </div>
  <!-- /sidebar menu -->

  <!-- /menu footer buttons -->
  {% comment %} <div class="sidebar-footer hidden-small">
    <a data-toggle="tooltip" data-placement="top" title="Settings">
      <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
    </a>
    <a data-toggle="tooltip" data-placement="top" title="FullScreen">
      <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
    </a>
    <a data-toggle="tooltip" data-placement="top" title="Lock">
      <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
    </a>
    <a data-toggle="tooltip" data-placement="top" title="Logout" href="login.html">
      <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
    </a>
  </div> {% endcomment %}
  <!-- /menu footer buttons -->
</div>